"""Context rotation — summarize accumulated context when it exceeds token limits.

When a pipeline has accumulated many reflections, feedback entries, and
convention notes, the context can grow beyond Claude's effective window.
ContextRotation monitors size and replaces verbose history with a condensed
summary generated by Claude Haiku (fast + cheap).

Learn: We estimate tokens at ~4 chars/token (conservative). When the total
memory context exceeds the threshold, we summarize the oldest content and
replace it in-place. This keeps the agent's context fresh without losing
important lessons.
"""

import logging
from pathlib import Path

from openclaw.config import settings

logger = logging.getLogger("openclaw.services.context_rotation")

CHARS_PER_TOKEN = 4


class ContextRotation:
    """Monitor and rotate context when it exceeds token thresholds."""

    def __init__(
        self,
        max_tokens: int | None = None,
        anthropic_client=None,
    ):
        self.max_tokens = max_tokens or settings.context_rotation_threshold_tokens
        self._client = anthropic_client

    async def check_and_rotate(
        self, worktree_path: str, current_token_estimate: int | None = None
    ) -> bool:
        """If tokens exceed threshold, summarize context.md via Claude Haiku.

        Args:
            worktree_path: Path to the git worktree
            current_token_estimate: Optional pre-computed estimate. If None,
                we compute from file sizes.

        Returns True if rotation was performed, False otherwise.
        """
        memory_dir = Path(worktree_path) / ".openclaw"

        if not memory_dir.exists():
            return False

        # Estimate total tokens from file sizes
        if current_token_estimate is None:
            total_chars = 0
            for f in memory_dir.iterdir():
                if f.is_file() and f.suffix == ".md":
                    total_chars += f.stat().st_size
            current_token_estimate = total_chars // CHARS_PER_TOKEN

        if current_token_estimate <= self.max_tokens:
            logger.debug(
                "Context size ~%d tokens, threshold %d — no rotation needed",
                current_token_estimate,
                self.max_tokens,
            )
            return False

        logger.info(
            "Context size ~%d tokens exceeds threshold %d — rotating",
            current_token_estimate,
            self.max_tokens,
        )

        # Summarize each memory file
        for f in sorted(memory_dir.iterdir()):
            if not f.is_file() or f.suffix != ".md":
                continue

            content = f.read_text()
            if len(content) < 500:
                continue  # Too short to bother summarizing

            summary = await self._summarize_context(content, f.name)
            f.write_text(
                f"# Summarized Context ({f.name})\n\n"
                f"_Auto-rotated at ~{current_token_estimate} tokens_\n\n"
                f"{summary}\n"
            )

        return True

    async def _summarize_context(
        self, context_text: str, filename: str
    ) -> str:
        """Call Claude Haiku for a condensed summary."""
        if self._client is None:
            try:
                import anthropic

                self._client = anthropic.AsyncAnthropic(
                    api_key=settings.anthropic_api_key
                )
            except ImportError:
                logger.warning("anthropic not installed, skipping summarization")
                # Fallback: truncate to first 2000 chars
                return context_text[:2000] + "\n\n[...truncated...]"

        try:
            response = await self._client.messages.create(
                model="claude-haiku-4-20250514",
                max_tokens=1024,
                messages=[
                    {
                        "role": "user",
                        "content": (
                            f"Summarize the following {filename} content into a "
                            f"concise set of key lessons, patterns, and actionable "
                            f"notes. Preserve critical details like file paths, "
                            f"function names, and specific error messages. Remove "
                            f"redundancy and timestamps.\n\n"
                            f"---\n\n{context_text}"
                        ),
                    }
                ],
            )
            return response.content[0].text
        except Exception as e:
            logger.warning("Failed to summarize via Claude: %s", e)
            return context_text[:2000] + "\n\n[...truncated due to API error...]"
